### ISSUE TITLE
undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by hounddog22030** [chef-cookbooks/windows#409]
### Cookbook version
2.1.0

### Chef-client version
Chef: 12.16.42

### Platform Details
Windows 2012 R2

### Scenario:
Trying to run cookbook 'ms_dotnet35'.  Was replicated with other cookbooks as well.

### Steps to Reproduce:
install cookbook ms_dotnet35.
run chef-client -z -o 'ms_dotnet35::default'

### Expected Result:
Executes cookbook ms_dotnet35 installing .net 3.5

### Actual Result:
Error (see below).

This was reproduced with other cookbooks that use windows cookbook as well.  By rolling back to 2.0.2 the issue goes away.

```
================================================================================[0m
[31mError executing action `install` on resource 'windows_feature[NetFx3]'[0m
================================================================================[0m

[0mNoMethodError[0m
-------------[0m
undefined method `key?' for nil:NilClass[0m

[0mResource Declaration:[0m
---------------------[0m
# In c:/windows/temp/Bisque/SqlServer/MssqlserverDefault/chefcache/cache/cookbooks/ms_dotnet35/recipes/default.rb
[0m
[0m 23:     windows_feature 'NetFx3' do
[0m 24:       action :install
[0m 25:       all true
[0m 26:       not_if { ::File.exist?('C:/Windows/Microsoft.NET/Framework/v3.5') }
[0m 27:     end
[0m 28:   else
[0m
[0mCompiled Resource:[0m
------------------[0m
# Declared in c:/windows/temp/Bisque/SqlServer/MssqlserverDefault/chefcache/cache/cookbooks/ms_dotnet35/recipes/default.rb:23:in `from_file'
[0m
[0mwindows_feature("NetFx3") do
[0m  provider LWRP provider windows_feature_dism from cookbook windows
[0m  action [:install]
[0m  retries 0
[0m  retry_delay 2
[0m  default_guard_interpreter :default
[0m  declared_type :windows_feature
[0m  cookbook_name "ms_dotnet35"
[0m  recipe_name "default"
[0m  all true
[0m  feature_name "NetFx3"
[0m  not_if { #code block }
[0mend
[0m
[0mPlatform:[0m
---------[0m
i386-mingw32[0m
```

**Comment by btm** [comment]
We're seeing this in the acceptance tests for chef-client in the 'top-cookbooks' test as well.

**Comment by tas50** [comment]
The windows default recipe is required with the dism changes that went in. Our tests missed this since they include that default recipe. I'm going to change things so the default recipe isn't necessary for the plugin to work.

**Comment by tas50** [comment]
This should be fixed in #411

**Comment by tas50** [comment]
This is fixed in the 2.1.1 release. Thanks for the report. The tests have been updated so we'll catch this in the future.

**Comment by nozpheratu** [comment]
@tas50 I'm using the 2.1.1 release and I'm still getting this.

**Comment by btm** [comment]
@nozpheratu can you share the stacktrace?

**Comment by nozpheratu** [comment]
@btm Sure. I'm using dism.

```ruby
windows_feature "Remote-Desktop-Services" do
  action :install
  not_if {reboot_pending?}
end
```

```bash
-----> Starting Kitchen (v1.14.0)
-----> Converging <default-mwrock-Windows2016>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.2.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (12.5.1)
       Transferring files to <default-mwrock-Windows2016>
       Starting Chef Client, version 12.5.1
       resolving cookbooks for run list: ["remote-vrt::default"]
       Synchronizing Cookbooks:
         - remote-vrt (0.1.0)
         - windows (2.1.1)
         - powershell (5.1.0)
         - ohai (4.2.2)
         - ms_dotnet (3.1.0)
         - chef_handler (2.0.0)
         - compat_resource (12.16.2)
       Compiling Cookbooks...
       Converging 3 resources
       Recipe: remote-vrt::default
         * user[guest2] action create (up to date)
         * group[Remote Desktop Users] action modify (up to date)
         * windows_feature[Remote-Desktop-Services] action install
           * ohai_plugin[dism_features] action create[2016-11-29T22:37:31+00:00] WARN: The Ohai plugin_path does not include C:\Users\vagrant\AppData\Local\Temp\kitchen/ohai/plugins. Ohai will reload on each chef-client run in order to add this directory to the path unless you modify your client.rb configuration to add this directory to plugin_path. See 'Ohai Settings' at https://docs.chef.io/config_rb_client.html
       [2016-11-29T22:37:31+00:00] WARN: Adding C:\Users\vagrant\AppData\Local\Temp\kitchen/ohai/plugins to the Ohai plugin path for this chef-client run only

             * directory[C:\Users\vagrant\AppData\Local\Temp\kitchen/ohai/plugins] action create (skipped due to not_if)
             * cookbook_file[C:\Users\vagrant\AppData\Local\Temp\kitchen/ohai/plugins/dism_features.rb] action create (up to date)
             * ohai[dism_features] action reload
        - re-run ohai and merge results into node attributes


           ================================================================================
           Error executing action `install` on resource 'windows_feature[Remote-Desktop-Services]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `key?' for nil:NilClass

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/remote-vrt/recipes/default.rb

            23: windows_feature "Remote-Desktop-Services" do
            24:   action :install
            25:   not_if {reboot_pending?}
            26: end
            27: # reboot "reboot" do

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/remote-vrt/recipes/default.rb:23:in `from_file'

           windows_feature("Remote-Desktop-Services") do
             provider LWRP provider windows_feature_dism from cookbook windows
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :windows_feature
             cookbook_name "remote-vrt"
             recipe_name "default"
             feature_name "Remote-Desktop-Services"
             not_if { #code block }
           end


       Running handlers:
       [2016-11-29T22:37:39+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-11-29T22:37:39+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 31 seconds
       [2016-11-29T22:37:39+00:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-11-29T22:37:39+00:00] FATAL: NoMethodError: windows_feature[Remote-Desktop-Services] (remote-vrt::default line 23) had an error: NoMethodError: undefined method `key?' for nil:NilClass
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-mwrock-Windows2016>.  Please see .kitchen/logs/default-mwrock-Windows2016.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by nozpheratu** [comment]
Not sure if this is related, but I can see that the "Remote-Desktop-Services" feature shows up as "Disabled" when I run the dism cmd executable. Would that have anything to do with it?

**Comment by hounddog22030** [comment]
Was it pulled yet?  I could not find evidence that it was pulled yet, but
I'm not sure

**Comment by nozpheratu** [comment]
@hounddog22030 Seems to be, but doesn't seem to fix the issue.

**Comment by mwrock** [comment]
must be coming from either https://github.com/chef-cookbooks/windows/blob/d144f3ecfc8c33473aacf6ec57fa7ac92cc3126c/providers/feature_dism.rb#L65 or https://github.com/chef-cookbooks/windows/blob/d144f3ecfc8c33473aacf6ec57fa7ac92cc3126c/providers/feature_dism.rb#L56.

Seems like the ohai plugin must not be setting the `dism_features`

**Comment by nozpheratu** [comment]
Here's my .kitchen.yml if it helps to reproduce the bug:
```yaml
---
driver:
  name: vagrant
  require_chef_omnibus: 12.5.1

provisioner:
  name: chef_zero

platforms:
  - name: mwrock/Windows2016
    transport:
      name: winrm
      max_threads: 1
    driver_config:
      network:
      - ["forwarded_port", {guest: 3389, host: 9833}]

suites:
  - name: default
    run_list:
      - recipe[remote-vrt::default]
    attributes:
      windows:
        feature_provider: 'dism'
```

The Chef recipe is simply:
```ruby
# install RDS
windows_feature "Remote-Desktop-Services" do
  action :install
  not_if {reboot_pending?}
end
```

**Comment by mwrock** [comment]
@nozpheratu this is caused by running with chef v12.5.1. You will have better luck running with an updated chef client or pinning to a v1 windows cookbook version.
