### ISSUE TITLE
Issue with Share

### ISSUE THREAD

**Issue by fourth-barryleonard** [chef-cookbooks/windows#501]
### Cookbook version

3.1.2

### Chef-client version

13.3.42

### Platform Details

Windows 2012 R2 on Azure

### Scenario:

Creating a new share with users as full control fails

### Steps to Reproduce:

file.rb recipe:

```
directory 'c:\\BarryTest' do
  action :create
end

windows_share 'BarryTest' do
  action :create
  path 'c:\\BarryTest'
  full_users ['everyone']
end
```

Test in /test/integration/barrytest-file/inspec/pester/file_spec.tests.ps1

```
$global:progressPreference = 'SilentlyContinue'

describe 'cookbook-fourth-barrytest::file' {
    context 'windows_share' {
       it "creates share BarryTest"  {
            "\\localhost\BarryTest" | Should Exist
        }

        $fileName = "\\localhost\BarryTest\change_file"
        it "Has Full Control permission on share to allow create, modify and delete"  {
            $f = New-Item $fileName -Type File
            $f.Name | Should Be "change_file"
            Remove-Item $fileName
        }
    }
}
```

### Expected Result:

When you run the recipe full control should be assigned to the share and all tests should pass

### Actual Result:

```
-----> Starting Kitchen (v1.17.0)
-----> Converging <barrytest-file-windows2012-r2-fourth>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing environments
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (13.3.42)
       Transferring files to <barrytest-file-windows2012-r2-fourth>
       Starting Chef Client, version 13.3.42
       resolving cookbooks for run list: ["cookbook-fourth-barrytest::file"]
       Synchronizing Cookbooks:
         - windows (3.1.3)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: cookbook-fourth-barrytest::file
         * directory[c:\BarryTest] action create
           - create new directory c:\BarryTest
         * windows_share[BarryTest] action create[2017-10-06T10:00:20+00:00] WARN: Failed to retrieve any security information about the share.

           - Creating share BarryTest

       Running handlers:
       Running handlers complete
       Chef Client finished, 2/2 resources updated in 07 seconds
       Finished converging <barrytest-file-windows2012-r2-fourth> (0m27.68s)
```

**Comment by smurawski** [comment]
Share permissions are not the same as file system permissions.  Share permissions allow users access only to the extent that NTFS permissions do.

For example, if the shared folder does not have NTFS permissions for the everyone group, even though full is specified, there would be no ability to create or read files.  Conversely, if everyone had full ntfs permissions, but only read share permissions, when accessing via SMB, the people in the everyone group would only be able to read files and not write them.

I'd retry your test and make sure (via the directory resource) that "everyone" has rights to the folder that was created.

**Comment by fourth-barryleonard** [comment]
Hey, thanks for your response. I'm cool with the difference between share and NTFS permissions but NTFS permissions aside here the share itself should have everyone with full control when it's created. When I execute that code the directory and share are created but under the permissions of the share the Everyone group still only has read. 

I'd expect the windows_share resource to create the share with Everyone full control regardless of what the NTFS permissions were. Park the tests aside, if I manually verify the share setup after a kitchen converge the Everyone group only has read which I don't think is correct.

Are you saying that if you execute the code above you end up with a share (different to NTFS permissions I know) with Everyone with Full control?

**Comment by troyready** [comment]
I'm seeing the same exact same behavior (Server 2012R2 on AWS using only local users)

**Comment by baurzhan-konurbayev** [comment]
Should be fixed here https://github.com/chef-cookbooks/windows/pull/515

**Comment by fourth-barryleonard** [comment]
I have tested the new version and this issue is still present for me as well
